### ISSUE TITLE
Kudos and thanks

### ISSUE THREAD

**Issue by simonp0420** [dpsanders/SatisfiabilityInterface.jl#17]
Just wanted to let you know that after watching your Juliacon presentation I installed and used this package for my map coloring application.  I wasn't able to get `SimpleSATSolver` working with it, but I managed to install `cryptominisat5` which worked flawlessly.  I had previously been using `SimpleGraphAlgorithms` which calls the `CBC` optimizer.  For a map graph with 179 vertices and chromatic number 4, `SimpleGraphAlgorithms` required about 41 seconds to do the coloring.  `SatisfiabilityInterface` colored the same graph in  less than 0.02 seconds!  Needless to say I am extremely pleased with this result.  Thanks for making it available!

**Comment by dpsanders** [comment]
Fantastic, that's great to hear! Thanks for letting me know.

Yes sorry, I haven't quite got all the plumbing ready to solve using SimpleSATSolver - I really need to do that!
